/**
 * Pure exporter: turn parsed `.http` files into a bash `curl` bundle script.
 *
 * Zero VS Code / undici / filesystem dependencies. The extension layer picks
 * the files to load, applies environment substitution, and hands us the
 * resulting `ParsedRequest`s; we produce a single bash script string plus a
 * structured report the caller can render into a webview.
 *
 * Non-HTTP inputs (`.grpc`, `.ws`) are declared unsupported and skipped with
 * a warning — `curl` cannot represent them, so a hard error would just annoy
 * the user in a mixed-tree export.
 */
import type { ParsedRequest } from '../parser.js';
import { toUndiciRequest } from '../request.js';
import { requestToCurl } from '../curl.js';

/**
 * One input file passed to the exporter. The extension layer decides whether
 * `requests` were resolved with real env values or left as `{{placeholders}}`.
 */
export interface ExportInputFile {
  /** Source path, workspace-relative or absolute — used only for grouping/labels. */
  path: string;
  /**
   * `http` inputs are supported; anything else is skipped with a warning so a
   * mixed `.requests/` tree export doesn't fail outright.
   */
  kind: 'http' | 'grpc' | 'ws' | 'unknown';
  /** Parsed HTTP requests (empty for non-http kinds). */
  requests?: ParsedRequest[];
}

export interface ExportCurlOptions {
  /**
   * Secret values (e.g. resolved from VS Code SecretStorage) that must never
   * appear in the output. Every occurrence is replaced with the placeholder
   * BEFORE any shell quoting, matching `requestToCurl`'s contract.
   */
  redact?: string[];
  redactPlaceholder?: string;
  /**
   * Optional header shown at the top of the bundle (e.g. timestamp,
   * environment name). One line, no shell metacharacters — the caller is
   * responsible for keeping it sane; we single-line-escape newlines.
   */
  banner?: string;
}

export interface ExportCurlWarning {
  /** Source path (or `'<unknown>'`). */
  path: string;
  /** Optional request identifier (name or `method url`). */
  request?: string;
  code:
    | 'unsupported-kind'
    | 'invalid-request'
    | 'secret-redacted'
    | 'no-requests';
  message: string;
}

export interface ExportCurlResult {
  /** The full bash script ready to be written to disk. */
  script: string;
  /** Number of `curl` commands actually emitted. */
  requestsWritten: number;
  /** Non-fatal issues; render these in the export report webview. */
  warnings: ExportCurlWarning[];
}

const DEFAULT_PLACEHOLDER = '***REDACTED***';

/**
 * Build a `curl` bundle from a set of parsed inputs.
 *
 * The output is a single-file bash script:
 *
 * ```bash
 * #!/usr/bin/env bash
 * # Generated by Reqit — do not edit by hand.
 * # <banner if provided>
 * set -euo pipefail
 *
 * # === <path> ===
 * # request: GET https://example.com/api
 * curl 'https://example.com/api'
 * ```
 *
 * The script is deterministic given the same inputs (no timestamps, no random
 * ordering) so it snapshots cleanly in tests.
 */
export function exportToCurlBundle(
  files: ExportInputFile[],
  options: ExportCurlOptions = {},
): ExportCurlResult {
  const warnings: ExportCurlWarning[] = [];
  const redact = (options.redact ?? []).filter((s) => s.length > 0);
  const placeholder = options.redactPlaceholder ?? DEFAULT_PLACEHOLDER;

  const lines: string[] = [
    '#!/usr/bin/env bash',
    '# Generated by Reqit — do not edit by hand.',
  ];
  if (options.banner && options.banner.length > 0) {
    // Collapse newlines so a stray banner cannot break out of the comment.
    lines.push(`# ${options.banner.replace(/\r?\n/g, ' ')}`);
  }
  lines.push('set -euo pipefail', '');

  let written = 0;
  let hadAnyRequests = false;

  for (const file of files) {
    if (file.kind !== 'http') {
      warnings.push({
        path: file.path,
        code: 'unsupported-kind',
        message:
          `Skipped ${file.kind} file — curl cannot represent ${file.kind} requests.`,
      });
      continue;
    }

    const requests = file.requests ?? [];
    if (requests.length === 0) {
      // Empty .http files are fine; note it but don't shout.
      warnings.push({
        path: file.path,
        code: 'no-requests',
        message: 'No requests found in file.',
      });
      continue;
    }

    hadAnyRequests = true;
    lines.push(`# === ${file.path} ===`);

    const redactLabel = (s: string): string =>
      redact.reduce((acc, secret) => acc.split(secret).join(placeholder), s);

    for (const req of requests) {
      const rawLabel = req.name ?? `${req.method} ${req.url}`;
      const label = redactLabel(rawLabel).replace(/\r?\n/g, ' ');
      try {
        const undiciOpts = toUndiciRequest(req);
        const curl = requestToCurl(undiciOpts, {
          redact,
          redactPlaceholder: placeholder,
        });
        lines.push(`# request: ${label}`);
        lines.push(curl);
        lines.push('');
        written++;

        // Sanity check: if a raw secret survived into the output, that's a
        // fatal-in-tests bug — surface it as a warning so it can never ship
        // silently.
        for (const secret of redact) {
          if (curl.includes(secret)) {
            warnings.push({
              path: file.path,
              request: label,
              code: 'secret-redacted',
              message:
                'Secret survived redaction pass — this is a bug, please report it.',
            });
          }
        }
      } catch (err) {
        warnings.push({
          path: file.path,
          request: label,
          code: 'invalid-request',
          message:
            err instanceof Error ? err.message : 'Failed to render request.',
        });
      }
    }
  }

  if (!hadAnyRequests && written === 0) {
    // Keep the script runnable even when nothing was exported so users don't
    // get a confusing "syntax error near unexpected token EOF".
    lines.push('# No exportable requests.', 'exit 0', '');
  }

  return {
    script: lines.join('\n'),
    requestsWritten: written,
    warnings,
  };
}
